# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3cbe91ff673a616b74de6e78ba237a68fdd050e661b6344c69e4e44da30ef8fafcfb21086b657a7280b7f191d94677fb43333a68f1bf1457e3ac724c20996b98

test:
  secret_key_base: 73fbcecd97b3452de635db1e93d5100fc10f5ec147a7d428938956ad1ec7c9e224187e1f21472b655bb29c46a149c328c9bb13a0a7ede57b5f34fb5522e5c70a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
